# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_title',
            field=models.CharField(max_length=1000),
        ),
    ]
