# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='subs',
            name='tech',
            field=models.CharField(max_length=30),
        ),
        migrations.AddField(
            model_name='technology',
            name='writeup',
            field=models.ManyToManyField(to='learnit.Subs'),
        ),
    ]
